coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: no
    changes: no

ignore:
  - "tests/"

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no

  codecov:
    token: de0cdd42-ce78-41bd-afd2-01228f709290
